import React from 'react';

const TermsPage: React.FC = () => {
    return (
        <section className="landing-section" style={{ textAlign: 'left', alignItems: 'flex-start' }}>
            <div style={{ maxWidth: '800px', margin: '0 auto', width: '100%' }}>
                <h1 style={{ fontSize: '2.5rem', marginBottom: '1rem' }}>Terms of Service</h1>
                <p style={{ color: 'var(--text-secondary)', marginBottom: '3rem' }}>Last updated: {new Date().toLocaleDateString()}</p>
                
                <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', lineHeight: 1.7, fontSize: '1.05rem', color: 'var(--text-primary)' }}>
                    <section>
                        <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>1. Agreement to Terms</h2>
                        <p>
                            By accessing or using Lucen ("the Service"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the Service. The Service is an AI workspace interface intended to facilitate interactions with various LLMs (Large Language Models).
                        </p>
                    </section>

                    <section>
                        <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>2. Use License</h2>
                        <p>
                            We grant you a personal, worldwide, royalty-free, non-assignable, and non-exclusive license to use the software provided to you as part of the Services. This license is for the sole purpose of enabling you to use and enjoy the benefit of the Services in the manner permitted by these terms.
                        </p>
                        <ul style={{ marginLeft: '1.5rem', marginTop: '1rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                            <li>You may not modify, attempt to reverse engineer, or extract the source code of the software unless permitted under an applicable open-source license.</li>
                            <li>You agree not to use the Service for any unlawful or prohibited activities.</li>
                            <li>You are responsible for safeguarding your account access credentials.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>3. Credits and Subscriptions</h2>
                        <p>
                            Lucen offers a credit-based subscription system. By subscribing to a paid tier via our payment processor, you agree to recurring billing until cancellation. 
                            Credits are allocated according to your subscription tier. Unused credits may expire at the end of the billing cycle depending on your plan specifications.
                        </p>
                    </section>

                    <section>
                        <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>4. Artificial Intelligence Outputs</h2>
                        <p>
                            Lucen relies on third-party APIs (such as OpenRouter, OpenAI, Anthropic) for generation. We do not guarantee the accuracy, reliability, or correctness of any outputs generated by the AI models. You agree that any actions taken based on AI-generated information are at your own risk.
                        </p>
                    </section>
                    
                    <section>
                        <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>5. Termination</h2>
                        <p>
                            We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms of Service. Upon termination, your right to use the Service will immediately cease.
                        </p>
                    </section>

                    <section>
                        <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>6. Limitation of Liability</h2>
                        <p>
                            In no event shall Lucen, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
                        </p>
                    </section>
                </div>
            </div>
        </section>
    );
};

export default TermsPage;
